from __future__ import annotations

import logging

import awkward as ak
import numba
import numpy as np
from numpy.typing import NDArray

from ..optmap import convolve
from ..units import attach_units, units_conv_ak

log = logging.getLogger(__name__)


def load_optmap_all(map_file: str) -> convolve.OptmapForConvolve:
    """Load an optical map file for later use with :func:`number_of_detected_photoelectrons`.

    Parameters
    ----------
    map_file
        file path to the map file.
    """
    return convolve.open_optmap(map_file)


def load_optmap(map_file: str, spm_det: str) -> convolve.OptmapForConvolve:
    """Load an optical map file for later use with :func:`number_of_detected_photoelectrons`.

    Parameters
    ----------
    map_file
        file path to the map file.
    spm_det
        detector name or the string ``"all"``. In the case of a detector name,
        it will load the optical map ``"/channels/{spm_det}"`` from the
        provided map file.
    """
    return convolve.open_optmap_single(map_file, spm_det)


def _nested_unflatten(data: ak.Array, lengths: ak.Array):
    return ak.unflatten(ak.unflatten(ak.flatten(data), ak.flatten(lengths)), ak.num(lengths))


def corrected_photoelectrons(
    simulated_pe: ak.Array,
    simulated_uids: ak.Array,
    data_pe: ak.Array,
    data_uids: ak.Array,
    *,
    seed: int | None = None,
) -> tuple[ak.Array, ak.Array]:
    r"""Correct the number of photoelectrons using forced trigger data.

    For every simulated event a corresponding forced trigger event in data is
    chosen and the resulting number of p.e. for each channel (i) is:

     .. math::

        n_i = n_{\text{sim},i} + n_{\text{data},i}

    .. warning::

       The number of supplied forced trigger events in data should ideally be
       more than that in the simulations. If this is not the case and
       "allow_data_reuse" is True then some data events will be used multiple
       times. This introduces a small amount of correlation between the
       simulated events, but is probably acceptable in most circumstances.

    Parameters
    ----------
    simulated_pe
        The number of number of detected pe per sipm channel.
    simulated_uids
        The unique identifier (uid) for each sipm hit.
    data_pe
        The collection of forced trigger pe.
    data_uids
        The uids for each forced trigger event.
    seed
        Seed for random number generator.

    Returns
    -------
    a tuple of the corrected pe and sipm uids.
    """
    rand = np.random.default_rng(seed=seed)
    rand_ints = rand.integers(0, len(data_pe), size=len(simulated_pe))

    selected_data_pe = data_pe[rand_ints]
    selected_data_uids = data_uids[rand_ints]

    # combine sims with data
    pe_tot = ak.concatenate([simulated_pe, selected_data_pe], axis=1)
    uid_tot = ak.concatenate([simulated_uids, selected_data_uids], axis=1)

    # sort by uid
    order = ak.argsort(uid_tot)
    pe_tot = pe_tot[order]
    uid_tot = uid_tot[order]

    # add an extra axis
    n = ak.run_lengths(uid_tot)

    # add another dimension
    pe_tot = _nested_unflatten(pe_tot, n)
    uid_tot = _nested_unflatten(uid_tot, n)

    # sum pe and take the first uid (should all be the same)
    corrected_pe = ak.sum(pe_tot, axis=-1)
    uid_tot = ak.fill_none(ak.firsts(uid_tot, axis=-1), np.nan)

    return corrected_pe, uid_tot


def detected_photoelectrons(
    num_scint_ph: ak.Array,
    particle: ak.Array,
    time: ak.Array,
    xloc: ak.Array,
    yloc: ak.Array,
    zloc: ak.Array,
    optmap: convolve.OptmapForConvolve,
    material: convolve.ScintMaterial,
    spm_detector: str,
    map_scaling: float = 1,
    map_scaling_sigma: float = 0,
) -> ak.Array:
    """Derive the number and arrival times of detected photoelectrons.

    From scintillator hits using an optical map.

    .. deprecated :: 0.8.5

        Use the other, more fine-granular and split processors
        :func:`number_of_detected_photoelectrons` and :func:`photoelectron_times` to
        replace this legacy processor.

    Parameters
    ----------
    num_scint_ph
        array of emitted scintillation photons, as generated by
        :func:`emitted_scintillation_photons`.
    particle
        array of particle PDG IDs of scintillation events.
    time
        array of timestamps of scintillation events.
    xloc
        array of x coordinate position of scintillation events.
    yloc
        array of y coordinate position of scintillation events.
    zloc
        array of z coordinate position of scintillation events.
    optmap
        the optical map loaded via py:func:`load_optmap`.
    material
        scintillating material name or material definition as used for
        :func:`pygeomoptics.scintillate.precompute_scintillation_params`.
    spm_detector
        SiPM detector name as used in the optical map.
    map_scaling
        scale the detection probability in the map for this detector by this factor.
    map_scaling_sigma
        if larger than zero, sample the used scaling factor for each (reshaped) event
        from a normal distribution with this standard deviation.
    """
    hits = ak.Array(
        {
            "num_scint_ph": units_conv_ak(num_scint_ph, "dimensionless"),
            "particle": units_conv_ak(particle, "dimensionless"),
            "time": units_conv_ak(time, "ns"),
            "xloc": units_conv_ak(xloc, "m"),
            "yloc": units_conv_ak(yloc, "m"),
            "zloc": units_conv_ak(zloc, "m"),
        }
    )

    scint_mat_params = convolve._get_scint_params(material)
    pe = convolve.iterate_stepwise_depositions_pois(
        hits, optmap, scint_mat_params, spm_detector, map_scaling, map_scaling_sigma
    )

    return attach_units(pe, "ns")


def emitted_scintillation_photons(
    edep: ak.Array, particle: ak.Array, material: convolve.ScintMaterial
) -> ak.Array:
    """Derive the number of emitted scintillation photons from scintillator hits.

    This processor converts energy depositions into a number of emitted
    scintillation photons.

    Parameters
    ----------
    edep
        array of deposited energy in scintillation events.
    particle
        array of particle PDG IDs of scintillation events.
    material
        scintillating material name or material definition as used for
        :func:`pygeomoptics.scintillate.precompute_scintillation_params`.

    Returns
    -------
    Awkward array of integer photon counts with the same nested list structure
    (shape) as the input `edep` array.
    """
    hits = ak.Array(
        {
            "edep": units_conv_ak(edep, "keV"),
            "particle": units_conv_ak(particle, "dimensionless"),
        }
    )

    scint_mat_params = convolve._get_scint_params(material)
    return convolve.iterate_stepwise_depositions_scintillate(hits, scint_mat_params)


def number_of_detected_photoelectrons(
    xloc: ak.Array,
    yloc: ak.Array,
    zloc: ak.Array,
    num_scint_ph: ak.Array,
    optmap: convolve.OptmapForConvolve,
    spm_detector: str,
    map_scaling: float = 1,
    map_scaling_sigma: float = 0,
    max_pes_per_hit: int = -1,
) -> ak.Array | tuple[ak.Array, NDArray]:
    """Derive the number of detected photoelectrons.

    This processor uses the provided optical map to convert emitted
    scintillation photons into detected photoelectrons for a single
    detector/channel.

    Parameters
    ----------
    xloc
        array of x coordinate position of scintillation events.
    yloc
        array of y coordinate position of scintillation events.
    zloc
        array of z coordinate position of scintillation events.
    num_scint_ph
        array of emitted scintillation photons, as generated by
        :func:`emitted_scintillation_photons`.
    max_pes_per_hit
        Maximum number of photoelectrons to generate for a single scintillation
        hit. Use ``-1`` to disable this limit.

    Warning
    -------
    The `max_pes_per_hit` argument cannot be used in a ``build_hit()`` config
    file, since a tuple is returned in this case.

    Returns
    -------
    Awkward array of integer p.e. counts with the same nested list structure
    (shape) as the input `num_scint_ph` array. If `max_pes_per_hit` is greater
    than zero, returns a tuple of the p.e. counts and a 1D boolean array that
    tells whether the maximum number of p.e.s was reached for the hit.
    """
    hits = ak.Array(
        {
            "xloc": units_conv_ak(xloc, "m"),
            "yloc": units_conv_ak(yloc, "m"),
            "zloc": units_conv_ak(zloc, "m"),
            "num_scint_ph": units_conv_ak(num_scint_ph, "dimensionless"),
        }
    )

    return convolve.iterate_stepwise_depositions_numdet(
        hits, optmap, spm_detector, map_scaling, map_scaling_sigma, max_pes_per_hit
    )


def photoelectron_times(
    num_det_ph: ak.Array,
    particle: ak.Array,
    time: ak.Array,
    material: convolve.ScintMaterial,
) -> ak.Array:
    """Derive the arrival times of scintillation photons.

    This processor samples an arrival time for each detected photon, given the
    particle type, material scintillation model, and emission time.

    Parameters
    ----------
    num_det_ph
        array of detected scintillation photons, as generated by
        :func:`emitted_scintillation_photons`.
    particle
        array of particle PDG IDs of scintillation events.
    time
        array of timestamps of scintillation events.
    material
        scintillating material name or material definition as used for
        :func:`pygeomoptics.scintillate.precompute_scintillation_params`.

    Returns
    -------
    Awkward array where each event contains a list of arrival times; the
    per-event list length is the sum of `num_det_ph` for that event (i.e.
    ``ak.sum(num_det_ph, axis=1)``).

    Notes
    -----
    The resulting times are unsorted along the innermost axis.
    """
    hits = ak.Array(
        {
            "num_det_ph": units_conv_ak(num_det_ph, "dimensionless"),
            "particle": units_conv_ak(particle, "dimensionless"),
            "time": units_conv_ak(time, "ns"),
        }
    )

    scint_mat_params = convolve._get_scint_params(material)
    pe = convolve.iterate_stepwise_depositions_times(hits, scint_mat_params)

    return attach_units(pe, "ns")


@numba.njit(cache=True)
def _cluster_photoelectrons_flat(
    offsets: NDArray,
    t: NDArray,
    a: NDArray,
    thr: float,
) -> tuple[NDArray, NDArray, NDArray]:
    """Numba-accelerated clustering kernel for the innermost list level.

    Parameters
    ----------
    offsets
        1D int64 array of list offsets (length = number of lists + 1).
    t
        1D array of sorted times for all elements.
    a
        1D array of amplitudes corresponding to times.
    thr
        maximum time span within a cluster.

    Returns
    -------
    out_t
        clustered times (first time in each cluster).
    out_a
        clustered amplitudes (sum of amplitudes in each cluster).
    counts
        number of clusters per original list.
    """
    n_lists = offsets.size - 1
    n = t.size

    out_t = np.empty(n, dtype=t.dtype)
    out_a = np.empty(n, dtype=a.dtype)
    counts = np.empty(n_lists, dtype=np.int64)

    out_k = 0
    for ilist in range(n_lists):
        s = offsets[ilist]
        e = offsets[ilist + 1]

        ncl = 0
        i = s
        while i < e:
            t0 = t[i]
            asum = 0.0
            j = i
            while j < e and (t[j] - t0) <= thr:
                asum += a[j]
                j += 1

            out_t[out_k] = t0
            out_a[out_k] = asum
            out_k += 1
            ncl += 1
            i = j

        counts[ilist] = ncl

    return out_t[:out_k], out_a[:out_k], counts


def _listoffset_chain(
    layout: ak.contents.Content,
) -> tuple[list[NDArray], ak.contents.NumpyArray]:
    """Extract the chain of offsets from nested :class:`ak.contents.ListOffsetArray`.

    Parameters
    ----------
    layout
        an awkward array layout.

    Returns
    -------
    offsets_chain
        list of int64 arrays, one per nested list depth, from outermost to
        innermost.
    content_numpy_layout
        the final :class:`ak.contents.NumpyArray` content node.
    """
    offsets_chain = []
    node = layout
    while isinstance(node, ak.contents.ListOffsetArray):
        offsets_chain.append(np.asarray(node.offsets, dtype=np.int64))
        node = node.content

    if not isinstance(node, ak.contents.NumpyArray):
        msg = f"expected ListOffsetArray(s) ending in NumpyArray; got {type(node).__name__}"
        raise TypeError(msg)

    return offsets_chain, node


def cluster_photoelectrons(
    times: ak.Array, amps: ak.Array, thr: float
) -> tuple[ak.Array, ak.Array]:
    """Cluster photoelectrons within the instrument time resolution.

    Clusters hits at ``axis=-1`` (innermost lists) such that within each cluster
    the time span (last time minus first time) does not exceed `thr`. This is
    useful for combining photoelectrons that arrive within the time resolution
    of the detector, treating them as a single detected pulse.

    The output time is the first time of each cluster; the amplitude is the sum
    of all amplitudes in the cluster.

    Parameters
    ----------
    times
        array of hit times, e.g. as returned by :func:`photoelectron_times`.
        Must be sorted in ascending order within each innermost list. Sorting
        is the caller's responsibility, unsorted input produces undefined
        behavior.
    amps
        array of amplitudes corresponding to `times`. Must have the same
        structure (nesting depth and list lengths) as `times`.
    thr
        maximum time span within a cluster (e.g. the detector time
        resolution), in nanoseconds.

    Returns
    -------
    clustered_times
        array with the same nesting structure, containing the first time of
        each cluster.
    clustered_amps
        array with the same nesting structure, containing the summed amplitude
        of each cluster.

    Raises
    ------
    ValueError
        If `times` and `amps` have different nesting depths or different
        numbers of elements.

    Examples
    --------
    >>> times = ak.Array([[0.0, 0.6, 1.1, 1.4, 2.3]])
    >>> amps = ak.Array([[1.0, 2.0, 3.0, 4.0, 5.0]])
    >>> t_out, a_out = cluster_photoelectrons(times, amps, thr=1.0)
    >>> ak.to_list(t_out)
    [[0.0, 1.1, 2.3]]
    >>> ak.to_list(a_out)
    [[3.0, 7.0, 5.0]]
    """
    times_p = ak.to_packed(units_conv_ak(times, "ns"))
    amps_p = ak.to_packed(units_conv_ak(amps, "dimensionless"))

    offsets_chain_t, tnode = _listoffset_chain(ak.to_layout(times_p))
    offsets_chain_a, anode = _listoffset_chain(ak.to_layout(amps_p))

    # minimal shape sanity: same nesting depth for list structure
    if len(offsets_chain_t) != len(offsets_chain_a):
        msg = "times and amps do not have the same list nesting depth"
        raise ValueError(msg)

    # verify that offsets match at each nesting level
    for i, (off_t, off_a) in enumerate(zip(offsets_chain_t, offsets_chain_a, strict=True)):
        if not np.array_equal(off_t, off_a):
            msg = f"times and amps have mismatched list lengths at nesting level {i}"
            raise ValueError(msg)

    # innermost offsets define the axis=-1 lists that must not mix
    inner_offsets = offsets_chain_t[-1]

    out_t, out_a, inner_counts = _cluster_photoelectrons_flat(
        inner_offsets, np.asarray(tnode.data), np.asarray(anode.data), thr
    )

    # rebuild: first make clustered axis=-1 lists
    cur_t = ak.unflatten(out_t, inner_counts)
    cur_a = ak.unflatten(out_a, inner_counts)

    # then rebuild outer list levels (working outward). each parent list has
    # counts = diff(parent_offsets)
    for parent_offsets in reversed(offsets_chain_t[:-1]):
        parent_counts = np.diff(parent_offsets).astype(np.int64)
        cur_t = ak.unflatten(cur_t, parent_counts)
        cur_a = ak.unflatten(cur_a, parent_counts)

    return attach_units(cur_t, "ns"), cur_a


def smear_photoelectrons(
    array: ak.Array, fwhm_in_pe: float, rng: np.random.Generator | None = None
) -> ak.Array:
    """Smear photoelectron pulse amplitudes.

    Returns an array of Gaussian distributed single-photoelectron amplitudes
    with the same shape as the input `array`. Negative samples are clipped to
    zero.

    Parameters
    ----------
    array
        array of photoelectrons, only its shape is used.
    fwhm_in_pe
        full width at half maximum of the single-photoelectron amplitude
        distribution, in photoelectron units.
    rng
        random number generator. If ``None``, :func:`numpy.random.default_rng`
        is used.
    """
    if rng is None:
        rng = np.random.default_rng()

    counts = ak.num(array)
    flat = rng.normal(loc=1, scale=fwhm_in_pe / 2.35482, size=ak.sum(counts))
    flat = np.where(flat < 0, 0, flat)

    return ak.unflatten(flat, counts)
